src/ZugferdProfiles.php, tests/DocumentTest.php
Unless I'm mistaken, it seems that the `contextparameter` for the `basic-wl` profile is incorrect.
It is currently `urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic` which corresponds to a `basic` profile instead of `urn:factur-x.eu:1p0:basicwl`.
=> Fix context parameter for wasic-wl profile

composer.json
Allow dependency on version 6 of `symfony/yaml` and `symfony/validator`. 
This library being compatible with php 8, there does not seem to be any problem or breaking change.
=> Allow symfony 6 dependency in composer.json

src/ZugferdObjectHelper.php, src/ZugferdProfiles.php, tests/testcases/issues/Issue18Test.php
For XRechnung 3.0 it is mandatory to define a Business Process Specified Document Context Parameter
=> Define businessprocess in profiles

build.ant.xml, examples/XRechnung3Simple.php, examples/XRechnung3SimpleQuick.php, src/quick/ZugferdQuickDescriptorXRechnung3.php
Move to Kosit Validation Tool 1.5.0 with Config for XRechnung 3.0
=> Move to Kosit Validation Tool 1.5.0 with Config for XRechnung 3.0

composer.json
The php-constraint currently contains `^8.0|^8.1`, which is equal to `^8.0`.
The caret contraint `^` will allow all non-breaking updates in semver, which means: `^8` = `>=8.0.0 <9.0.0`. The current usage of it could lead to missinterpretation.
[Composer Docs](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)
[Semver Checker](https://jubianchi.github.io/semver-check/#/^8/8.3.2)
=> Fixed php requirement - caret contraint means all non-breaking version

src/ZugferdDocumentBuilder.php
Fixes https://github.com/horstoeko/zugferd/issues/53
=> addDocumentPaymentMeanToDirectDebit() now contains $creditorReferenceID parameter

src/ZugferdDocumentBuilder.php
Usually, when people send payment via credit transfer, they are supposed to enter a intended purpose/reference.
So I think it would be good to add this argument to addDocumentPaymentMeanToCreditTransfer().
(I think after that, the payment stuff is perfect :-) )
=> addDocumentPaymentMeanToCreditTransfer() now contains $paymentReference parameter

src/ZugferdDocumentPdfBuilder.php
=> Add static factory for existing files

src/ZugferdDocumentBuilder.php, src/ZugferdDocumentPdfReader.php
ZUGFeRD 1.0: file name »ZUGFeRD-invoice.xml«
ZUGFeRD 2.0: file name »zugferd-invoice.xml«
ZUGFeRD 2.1 and Factur-X: file name  »factur-x.xml«
Since unix systems treat filenames case sensitive, it is important to distinct between ZUGFeRD-invoice.xml and zugferd-invoice.xml. I have also added the ZUGFeRD version numbers as comment next to the name. And I fixed a typo in the constant name.
=> ZugferdDocumentPdfReader accepts ZUGFeRD 1.0 filenames on unix systems

README.md, src/ZugferdSettings.php, src/jms/ZugferdTypesHandler.php, tests/testcases/SettingsTest.php
Related to #59 
Reviewer:  @danielmarschall 
In some special cases, it may be necessary to define the number of decimal places for a specific XML path. This can now be done with an extension of the ``ZugferdSettings``. An XML path is defined together with the number of digits of the number. This currently affects the serialization of 
- minimum\udt\AmountType
- basic\udt\AmountType
- basicwl\udt\AmountType
- en16931\udt\AmountType
- extended\udt\AmountType
- basic\udt\QuantityType
- basicwl\udt\QuantityType
- en16931\udt\QuantityType
- extended\udt\QuantityType
- basic\udt\PercentType
- basicwl\udt\PercentType
- en16931\udt\PercentType
- extended\udt\PercentType
The following methods have been added
- getSpecialDecimalPlacesMaps
- getSpecialDecimalPlacesMap
- setSpecialDecimalPlacesMaps
- …
=> Define decimal places for node paths

src/ZugferdDocumentBuilder.php, src/ZugferdDocumentReader.php
There are multiple functions to add tax registration of various participants which share parameters, code and documentation.
I guess the order of the two parameters was once reversed and thereby some documentation errors emerged.
I stumbled upon it while comparing the ZugferdQuickDescriptor example with the corresponding documented source code to be able to understand all the parameters.
Fixes #72
=> #72 Fixed documentation for *TaxRegistration-Methods

src/ZugferdDocumentBuilder.php
Test to see if the form suits you #65
=> [TEST-FEATURE] Detailed Input Value References in DocumentBuilder

src/ZugferdDocumentBuilder.php, tests/testcases/BuilderEn16931Test.php, tests/testcases/BuilderExtendedTest.php, tests/testcases/BuilderMinimumTest.php
Added methods "addDocumentSellerId" and "addDocumentBuyerId" for adding additional ids (not global ids) for seller and buyer (#90)
fixed #90
=> Added methods "addDocumentSellerId" and "addDocumentBuyerId" for adding additional ids (not global ids) for seller and buyer (#90)

src/ZugferdDocumentBuilder.php, tests/testcases/BuilderEn16931Test.php, tests/testcases/BuilderExtendedTest.php, tests/testcases/BuilderMinimumTest.php
There are other trade parties which can have multiple IDs:
ShipToTradeParty
UltimateShipToTradeParty
ShipFromTradeParty
InvoicerTradeParty
InvoiceeTradeParty
PayeeTradeParty
fixes #96
=> Add multiple IDs for several trade parties (#96)

src/ZugferdPdfWriter.php
A customer requires to receive only a single XML with a PDF embedded as base64.
This task was easy to manage using addDocumentAdditionalReferencedDocument().
I wanted to avoid having a XML containing a PDF which itself contains an XML (Matrjoschka), so I just did a XML containing a PDF.
Although not required, I thought that it would be a nice touch if the embedded PDF was PDF/A-3B instead of a plain PDF. [So, I wrote a method](https://gist.github.com/danielmarschall/8f4788ef4ff3b41ff00ba2057acc3234) based on ZugferdPdfWriter, which converts a plain PDF to PDF/A-3B (without attachments).
ZugferdPdfWriter has the problem that it does not write any metadata information if no files are included.
This PR fixes the issue.
While it does not affect the "normal usage" of this library, it fixes a …
=> Fix ZugferdPdfWriter not outputting metadata if there are no files

build/phpunit.xml, src/ZugferdProfileResolver.php, tests/assets/invalid.xml, tests/testcases/issues/Issue104Test.php
#104 ProfileResolver should raise ZugferdUnknownXmlContentException when XML content is not valid
=> #104 ProfileResolver should raise ZugferdUnknownXmlContentException when XML content is not valid

src/ZugferdDocumentPdfReader.php
Added readAndGuessFromContent to ZugferdDocumentPdfReader
=> #107 Added readAndGuessFromContent to ZugferdDocumentPdfReader

src/ZugferdDocumentReader.php, tests/testcases/PdfReaderEn16931AllowanceChargeTest.php, tests/testcases/PdfReaderEn16931Test.php, tests/testcases/PdfReaderExtended2Test.php, tests/testcases/PdfReaderExtendedTest.php, tests/testcases/PdfReaderMinimumTest.php, tests/testcases/PdfReaderXRechnungTest.php, tests/testcases/ReaderBasicTest.php, tests/testcases/ReaderEn16931AllowanceChargeTest.php, tests/testcases/ReaderEn16931Test.php, tests/testcases/ReaderExtended2Test.php, tests/testcases/ReaderExtendedTest.php, tests/testcases/ReaderXRechnungTest.php
The following functions were missing in ZugferdDocumentReader.php to get the Seller electronic address (BT-34) an the Buyer electronic address (BT-49):
* getDocumentSellerCommunication
* getDocumentBuyerCommunication
=> #136 Added "getDocumentSellerCommunication" and "getDocumentBuyerCommunication" to ZugferdDocumentReader

examples/En16931PdfBuilder.php, src/ZugferdDocumentPdfBuilderAbstract.php
Due to a missing parameter when calling “importPage”, existing hyperlinks may have been discarded
Fixes #139 
Bug fix (non-breaking change which fixes an issue)
=> #139 Fixed ZugferdDocumentPdfBuilder brakes Hyperlink

examples/En16931PdfBuilder.php, src/ZugferdDocumentPdfBuilderAbstract.php
#147 Allow "Source" for XML attachment relationship, added quick accessor to switch to "Data", "Alternative" or "Source" relation ship
=> #147 Allow "Source" for XML attachment relationship, added quick accessor to switch to "Data", "Alternative" or "Source" relation ship

examples/ExtendedSimple.php, src/ZugferdSettings.php, src/jms/ZugferdTypesHandler.php, tests/testcases/SettingsTest.php
Handle the decimal places of a measure. For that new methods are added to ZugferdSettings:
*  getMeasureDecimals
*  setMeasureDecimals
Added handling of measure-decimals to ``ZugferdTypesHandler``
Fixes #169
=> #169 Handle Decimals of the measure type

composer.json
In this commit https://github.com/horstoeko/zugferd/commit/655a7c9dd12ad4a7b171aecbdbb3f152c6763bbc these files were moved into a subfolder. Directories longer exist
https://github.com/Roave/BackwardCompatibilityCheck `Roave\BetterReflection\SourceLocator\Type\Composer\Psr\Psr4Mapping` check will fail
=> Fix composer autoload psr-4 mapping

src/ZugferdDocumentPdfBuilderAbstract.php, src/ZugferdPdfWriter.php, src/exception/ZugferdExceptionCodes.php, src/exception/ZugferdInvalidArgumentException.php, tests/testcases/PdfBuilderEn16931Test.php
Used to write unit tests where input files A & B should consistently produce the same output PDF C. The random bits and timestamps make this challenging
See  issue #201
=> [ENH] Add deterministic Mode to ZugferdDocumentPdfBuilderAbstract

build/phpunit.xml, src/ZugferdObjectHelper.php, tests/assets/xml_issue_206.xml, tests/testcases/issues/Issue206Test.php
Fixes handling of datetime-values with linebreaks
Fixes #206 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> #206 Fix DateTime-Handling (strings with linebreaks)

examples/KositValidator.php, src/ZugferdKositValidator.php
If you have a running instances of the Kosit-Validator in Daemon-Mode (https://github.com/itplr-kosit/validator/blob/main/docs/daemon.md) you can optionally check against this Daemon via HTTP
=> [ENH] ZugferdKositValidator can optionally call a running Validator in Daemon-Mode via HTTP

src/codes/ZugferdAccountingAccountsClassificationTypes.php, src/codes/ZugferdAllowanceCodes.php, src/codes/ZugferdChargeCodes.php, src/codes/ZugferdCountryCodes.php, src/codes/ZugferdCurrencyCodes.php, src/codes/ZugferdDutyTaxFeeCategories.php, src/codes/ZugferdElectronicAddressScheme.php, src/codes/ZugferdInvoiceType.php, src/codes/ZugferdItemTypeIdentificationCodes.php, src/codes/ZugferdPaymentMeans.php, src/codes/ZugferdReferenceCodeQualifiers.php, src/codes/ZugferdSchemeIdentifiers.php, src/codes/ZugferdTextSubjectCodeQualifiers.php, src/codes/ZugferdUnitCodes.php, src/codes/ZugferdVATExemptionReasonCode.php
Adding the backed enums in a new namespace, keeping the original names.
=> adding backed enums for codelists

src/ZugferdPdfWriter.php
When using rand(128, 256), the value 256 can be randomly generated, which results in the hex value “00”. However, this is not compliant with PDF/A-3.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* OS:
* OS Version:
* PHP Version:
=> Fixed incompatible PDF/A header bytes

src/ZugferdDocumentPdfBuilderAbstract.php, src/ZugferdDocumentPdfMerger.php
The isFile() method in ZugferdDocumentPdfBuilderAbstract is currently declared as private, making it impossible to override. This poses the following issues:
Security Risk: The isFile() method determines whether the input is a filename or raw content, implicitly loading file contents when a valid filename is provided. This behavior can inadvertently allow unwanted file access.
Performance Issue: Implicitly interpreting input as a file or content adds unnecessary overhead, especially if the use case requires the input to always be treated as raw content.
If the isFile() method were protected, developers could override it to ensure the input is always interpreted as raw content, avoiding implicit file loading.
The same issue applies to the xmlDataIsFile() method in ZugferdDocumentPdfMerger. …
=> [ENH] #244 Make isFile() and xmlDataIsFile() methods overridable

src/ZugferdDocument.php, src/ZugferdSettings.php, tests/testcases/SettingsTest.php
Currently, this library uses the JMS\Serializer\SerializerBuilder, which offers the method setCacheDir() to define a caching directory. However, there is no mechanism in the static ZugferdSettings object to specify the cache directory, which could then be passed when constructing the SerializerBuilder.
Adding this feature would allow users to configure the cache directory via the ZugferdSettings object, improving flexibility and maintainability for applications that use this library.
Fixes #245 
=> [ENH] #245 Add Support for Setting SerializerBuilder Cache Directory

src/ZugferdDocumentPdfBuilderAbstract.php
Creator tool name was set in XMP data only. Additionally, FPDF allows to set creator name also via SetCreator().
File info before change (via Chrome):
File info after change:
=> Add creator tool name to meta data

build/phpunit.xml, src/ZugferdDocumentReader.php, tests/assets/xml_issue_268.xml, tests/assets/xml_issue_268_extended.xml, tests/testcases/BuilderEn16931Test.php, tests/testcases/BuilderExtendedTest.php, tests/testcases/BuilderMinimumTest.php, tests/testcases/PdfReaderEn16931AllowanceChargeTest.php, tests/testcases/PdfReaderEn16931Test.php, tests/testcases/PdfReaderExtended2Test.php, tests/testcases/PdfReaderExtendedTest.php, tests/testcases/PdfReaderMinimumTest.php, tests/testcases/PdfReaderXRechnungTest.php, tests/testcases/ReaderBasicTest.php, tests/testcases/ReaderEn16931AllowanceChargeTest.php, tests/testcases/ReaderEn16931Test.php, tests/testcases/ReaderExtended2Test.php, tests/testcases/ReaderExtendedTest.php, tests/testcases/ReaderXRechnungTest.php, tests/testcases/issues/Issue270Test.php
Added methods to read ReceivableSpecifiedTradeAccountingAccounts on document- and position-level
Fixes #270
=> [ENH] #270 Added methods to read ReceivableSpecifiedTradeAccountingAccounts on document- and position-level

src/ZugferdDocumentBuilder.php, src/ZugferdObjectHelper.php, tests/testcases/BuilderEn16931Test.php, tests/testcases/BuilderExtendedTest.php, tests/testcases/BuilderMinimumTest.php
Added support for PartialPaymentAmount (BT-X-275) on PaymentTerms. This is only available in the EXTENDED-Profile
Fixes #277 
Unit and integration tests on
- BuilderMinimumTest
- BuilderEn16931Test
- BuilderExtendedTest
=> #277 Added support for PartialPaymentAmount (BT-X-275) on PaymentTerms (EXTENDED-Profile only)

src/ZugferdDocumentBuilder.php, src/ZugferdDocumentReader.php, src/ZugferdObjectHelper.php, tests/assets/xml_extended_1.xml, tests/testcases/BuilderEn16931Test.php, tests/testcases/BuilderExtendedTest.php, tests/testcases/BuilderMinimumTest.php, tests/testcases/ObjectHelperEn16931Test.php, tests/testcases/ObjectHelperExtendedTest.php, tests/testcases/PdfReaderEn16931AllowanceChargeTest.php, tests/testcases/PdfReaderEn16931Test.php, tests/testcases/PdfReaderExtended2Test.php, tests/testcases/PdfReaderExtendedTest.php, tests/testcases/PdfReaderXRechnungTest.php, tests/testcases/ReaderBasicTest.php, tests/testcases/ReaderEn16931AllowanceChargeTest.php, tests/testcases/ReaderEn16931Bank1Test.php, tests/testcases/ReaderEn16931Bank2Test.php, tests/testcases/ReaderEn16931Test.php, tests/testcases/ReaderExtended2Test.php, tests/testcases/ReaderExtendedTest.php, tests/testcases/ReaderXRechnungTest.php
Addes support for ApplicableTradePaymentPenaltyTerms (BG-X-43). This includes all attributes for ApplicableTradePaymentPenaltyTerms
Fixes #279 
All Unit Tests for ``ZugferdDocumentBuilder`` and ``ZugferdDocumentReader``
=> #279 Add support for ApplicableTradePaymentPenaltyTerms (BG-X-43)

src/ZugferdProfiles.php, tests/testcases/ReaderXRechnungAttachedBinaryObjectTest.php, tests/testcases/ReaderXRechnungTest.php
Changed PDF Conformancelevel for Profile XRechnung to "XRECHNUNG"
Fixes #286 
=> #286 Changed PDF Conformancelevel for Profile XRechnung to "XRECHNUNG"

src/ZugferdDocumentReader.php
DocumentReader uses a wrong path to extract BT-X-145
Fixes #299 
=> #299 ZugferdDocumentReader::getDocumentDeliveryTerms uses the wrong path
