horstoeko/zugferd

composer.json

Version bump of smalot/pdfparser to allow php >=8.0

---

src/ZugferdDocumentBuilder.php

#12 Added method setDocumentRoutingId to ZugferdDocumentBuilder

---

src/ZugferdDocumentPdfBuilder.php
tests/testcases/PdfBuilderEn16931Test.php

Adds the option to return the PDF as a string

Add string output as option

---

examples/En16931PdfMerger.php
examples/invoice_1.xml
src/ZugferdDocumentAbstractPdfBuilder.php
src/ZugferdDocumentPdfBuilder.php
src/ZugferdDocumentPdfMerger.php

New class ZugferdDocumentPdfMerger was added. This class can merge existing XML to an existing PDF

Issue 14 - Introducing ZugferdDocumentPdfMerger

---

build.ant.xml

Cleanup Buildscript (More flexible with more variables)

Cleanup Buildscript (More flexible with more variables)

---

.github/workflows/build.php82.ant.yml
.github/workflows/build.php83.ant.yml
README.md

Newer PHP-releases seem supported just fine. I think, tests would be a good idea nontheless.

Run tests also for newer PHP releases

---

.gitignore
README.md
composer.json
examples/KositValidator.php
src/ZugferdKositValidator.php

Prototype of the ``ZugferdKositValidator``-Class. At present, this feature is still to be considered __experimental__.

Kositvalidator

---

src/ZugferdKositValidator.php

ZugferdKositValidator -> Made message bag type constants private

ZugferdKositValidator -> Made message bag type constants private

---

build/phpunit.xml
tests/testcases/issues/Issue43Test.php

Added Test for Issue #43

---

src/yaml/basic/ram/HeaderTradeSettlementType.yml
src/yaml/basic/ram/TradeAddressType.yml

Fix for "Cannot access private property" see #67

Fix for "Cannot access private property"

---

src/ZugferdDocumentBuilder.php

Revert "Update ZugferdDocumentBuilder.php"

---

src/ZugferdDocumentBuilder.php

Multiple Deprecation Warnings in 1.0.54 (#89)

---

src/ZugferdProfileResolver.php

Added missing call to libxml_clear_errors in ZugferdProfileResolver

#108 Added missing call to libxml_clear_errors in ZugferdProfileResolver

---

src/ZugferdDocumentBuilder.php
src/ZugferdDocumentReader.php
src/ZugferdKositValidator.php
src/codelists/ZugferdSchemeIdentifiers.php
src/exception/ZugferdUnknownProfileIdException.php
tests/testcases/BuilderMinimumTest.php

Codestyle and PHPDoc fixes

---

build/phpunit.xml
src/ZugferdDocumentBuilder.php
tests/testcases/issues/Issue113Test.php

#113 Fix for ZugferdDocumentBuilder ->setDocumentSummation() $taxTotalAmount parametter is not optional

Fix for ZugferdDocumentBuilder ->setDocumentSummation() $taxTotalAmount parametter is not optional

---

src/ZugferdDocumentReader.php
src/yaml/extended/ram/ReferencedDocumentType.yml
tests/testcases/PdfReaderExtended2Test.php
tests/testcases/ReaderExtended2Test.php

Fix name parameter in additional referenced documents -> changed type of  "name"-parameter to TextType

#130 Fix name parameter in additional referenced documents

---

src/ZugferdDocument.php
src/ZugferdDocumentPdfMerger.php
src/ZugferdDocumentValidator.php
tests/TestCase.php
tests/testcases/BuilderEn16931Test.php
tests/testcases/BuilderExtendedTest.php
tests/testcases/BuilderMinimumTest.php
tests/testcases/DocumentTest.php
tests/testcases/PdfBuilderEn16931Test.php
tests/testcases/PdfReaderEn16931AllowanceChargeTest.php
tests/testcases/PdfReaderEn16931Test.php
tests/testcases/PdfReaderExtended2Test.php
tests/testcases/PdfReaderExtendedTest.php
tests/testcases/PdfReaderMinimumTest.php
tests/testcases/PdfReaderMultipleAttachmentsTest.php
tests/testcases/PdfReaderXRechnungTest.php
tests/testcases/ReaderBasicTest.php
tests/testcases/ReaderEn16931AllowanceChargeTest.php
tests/testcases/ReaderEn16931Bank1Test.php
tests/testcases/ReaderEn16931Bank2Test.php
tests/testcases/ReaderEn16931Test.php
tests/testcases/ReaderExtended2Test.php
tests/testcases/ReaderExtendedTest.php
tests/testcases/ReaderXRechnungAttachedBinaryObjectTest.php
tests/testcases/ReaderXRechnungTest.php
tests/testcases/issues/Issue18Test.php

Sealed class ZugferdDocument

---

src/ZugferdProfileResolver.php
src/ZugferdProfiles.php
tests/testcases/ProfileResolverTest.php

#150  Added support for alternative context parameters

#150  Added support for alternative context parameters

---

examples/XRechnung3Simple.php
src/ZugferdDocumentBuilder.php

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #180 #181

#181 Add method for adding payment terms in special XRechnung-Syntax

---

src/quick/ZugferdQuickDescriptor.php

Fix for duplicated VAT breakdown
Fixes #185

#185 Fixed duplicated VAT Breakdown in QuickDescriptor

---

src/codelistsenum/ZugferdAccountingAccountsClassificationTypes.php
src/codelistsenum/ZugferdAllowanceCodes.php
src/codelistsenum/ZugferdChargeCodes.php
src/codelistsenum/ZugferdCountryCodes.php
src/codelistsenum/ZugferdCurrencyCodes.php
src/codelistsenum/ZugferdDutyTaxFeeCategories.php
src/codelistsenum/ZugferdElectronicAddressScheme.php
src/codelistsenum/ZugferdInvoiceType.php
src/codelistsenum/ZugferdItemTypeIdentificationCodes.php
src/codelistsenum/ZugferdPaymentMeans.php
src/codelistsenum/ZugferdReferenceCodeQualifiers.php
src/codelistsenum/ZugferdSchemeIdentifiers.php
src/codelistsenum/ZugferdTextSubjectCodeQualifiers.php
src/codelistsenum/ZugferdUnitCodes.php
src/codelistsenum/ZugferdVATExemptionReasonCode.php

Added Codelists as Enum (see PR #223)

[ENH] Added Codelists as Enum (see PR #223)

---

src/ZugferdDocumentPdfBuilderAbstract.php
src/ZugferdDocumentPdfMerger.php

Fixed issues regarding the use of is_file
Fixes #253

[FIX] #253 Fixed issues regarding the use of is_file

---

src/ZugferdObjectHelper.php

Added support for Date-Format 610
Fixes #259 

[ENH] #259 Added support for Date-Format 610

---

src/yaml/basic/rsm/CrossIndustryInvoice.yml
src/yaml/basic/rsm/CrossIndustryInvoiceType.yml
src/yaml/basicwl/rsm/CrossIndustryInvoice.yml
src/yaml/basicwl/rsm/CrossIndustryInvoiceType.yml
src/yaml/en16931/rsm/CrossIndustryInvoice.yml
src/yaml/en16931/rsm/CrossIndustryInvoiceType.yml
src/yaml/extended/rsm/CrossIndustryInvoice.yml
src/yaml/extended/rsm/CrossIndustryInvoiceType.yml
src/yaml/minimum/rsm/CrossIndustryInvoice.yml
src/yaml/minimum/rsm/CrossIndustryInvoiceType.yml
tests/testcases/BuilderEn16931Test.php
tests/testcases/BuilderExtendedTest.php
tests/testcases/BuilderMinimumTest.php

Cleanup namespaces
Fixes #274 
Unit and Integration tests

#274 Fix namespaces (Removed unused old namespaces)

---

build/phpunit.xml
make/genmethoddocs.php
src/ZugferdDocument.php
src/ZugferdDocumentProfileConverter.php
tests/testcases/ProfileConverterTest.php

Convert between profiles
Fixes #263 

#263 Added ZugferdDocumentProfileConverter

---

src/ZugferdDocumentPdfBuilderAbstract.php

Added option to not open the attachment pane
Fixes #294 

[ENH] Option to not open the attachment pane
